DATA:
  data_root: data/preprocessed/custom_3d  # data/preprocessed/FOLDERNAME/custom_3d
  data_root_2d_fused_feature: data/custom_multiview_openseg
  feature_2d_extractor: openseg
  aug: False
  eval_all: True
  voxel_size: 0.02
  input_color: False
  use_shm: False
  
TEST:
  split:  # train, val, test - default is None
  labelset: custom18
  prompt_eng: True
  mark_no_feature_to_unknown: True
  feature_type: 'distill' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: True
  eval_iou: False
  vis_input: True
  vis_pred: True
  vis_gt: False
  test_workers: 0
  test_gpu: [0]
  test_batch_size: 1
  model_path: 'https://cvg-data.inf.ethz.ch/openscene/models/matterport_openseg.pth.tar'  # scannet_openseg.pth.tar
  save_folder:
  foldername:
  test_repeats: 1
  arch_3d: MinkUNet18A
  manual_seed: 3407

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0